#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-demo-ns
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
