#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-demo-ns
  annotations:
    metallb.universe.tf/loadBalancer-ip: "192.168.1.41"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
