apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-demo
  namespace: guestbook-demo-ns
  labels:
    app.kubernetes.io/name: guestbook-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook-demo
    spec:
      containers:
        - name: guestbook-demo
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          ports:
           - name: http
             containerPort: 80
