#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: guestbook-svc
  namespace: guestbook-demo-ns
  annotations:
    metallb.io/loadBalancerIPs: 192.168.1.42
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: guestbook-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
