#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: guestbook-demo-ns
spec:
  selector:
    app.kubernetes.io/name: guestbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
